#!/usr/bin/env python3
"""
Vietnam GIS Explorer – FastAPI Web Application.

Serves interactive maps and data generated by pipeline.py.

Usage:
    uvicorn app:app --reload --host 0.0.0.0 --port 8000
"""

import io
import json
import shutil
from pathlib import Path
from typing import Optional, Dict

import math

import numpy as np
import rasterio
from rasterio.warp import reproject, Resampling, transform_bounds
from rasterio.transform import from_bounds
import geopandas as gpd
from shapely.geometry import Polygon, MultiPolygon, GeometryCollection
from shapely.ops import unary_union
from PIL import Image
from fastapi import FastAPI, HTTPException, Query
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse, Response, JSONResponse

from pipeline import (
    PROVINCE_MERGER_2025, GSO_PROVINCE_DATA, GADM_URL,
    LANDCOVER_CLASSES, _normalize_vn, download_file,
)

from pyproj import Transformer

import matplotlib
matplotlib.use("Agg")
import matplotlib.cm as mpl_cm

_TO_3857 = Transformer.from_crs("EPSG:4326", "EPSG:3857", always_xy=True)

# ── Paths ──────────────────────────────────────────────
BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data" / "province"
GADM_CACHE = BASE_DIR / "data" / "gadm41_VNM_1.json"
LEGACY_STATIC_DIR = BASE_DIR / "static"
FRONTEND_DIST_DIR = BASE_DIR / "frontend" / "dist"
FRONTEND_ASSETS_DIR = FRONTEND_DIST_DIR / "assets"

# ── Layer rendering config ─────────────────────────────
LAYER_CONFIG: Dict[str, dict] = {
    "hillshade":  {"cmap": "gray",        "vmin": 0,    "vmax": 255},
    "dem":        {"cmap": "gist_earth",   "vmin": 0,    "vmax": 2500},
    "slope":      {"cmap": "YlOrRd",       "vmin": 0,    "vmax": 45},
    "aspect":     {"cmap": "hsv",          "vmin": 0,    "vmax": 360},
}

# Per-province auto-scale cache: {(province_safe, layer): (vmin, vmax)}
_stats_cache: Dict[tuple, tuple] = {}

# ── Transparent 256x256 tile (lazy) ────────────────────
_EMPTY_PNG: Optional[bytes] = None

def _empty_tile() -> bytes:
    global _EMPTY_PNG
    if _EMPTY_PNG is None:
        buf = io.BytesIO()
        Image.new("RGBA", (256, 256), (0, 0, 0, 0)).save(buf, "PNG")
        _EMPTY_PNG = buf.getvalue()
    return _EMPTY_PNG

# ── FastAPI app ────────────────────────────────────────
app = FastAPI(title="Vietnam GIS Explorer", version="1.0")
if LEGACY_STATIC_DIR.exists():
    app.mount("/static", StaticFiles(directory=str(LEGACY_STATIC_DIR)), name="static")
if FRONTEND_ASSETS_DIR.exists():
    app.mount("/assets", StaticFiles(directory=str(FRONTEND_ASSETS_DIR)), name="assets")

# ── Helpers ────────────────────────────────────────────

def _safe(name: str) -> str:
    return name.replace(" ", "_").replace(".", "")

def _pdir(name: str) -> Path:
    return DATA_DIR / _safe(name)

def _resolve(query: str) -> Optional[str]:
    """Match a query string to a canonical 2025 province name."""
    q = _normalize_vn(query)
    for new_name in PROVINCE_MERGER_2025:
        if _normalize_vn(new_name) == q or q in _normalize_vn(new_name):
            return new_name
    for new_name, old_names in PROVINCE_MERGER_2025.items():
        for old in old_names:
            if _normalize_vn(old) == q or q in _normalize_vn(old):
                return new_name
    return None

def _gso(name: str) -> dict:
    old_names = PROVINCE_MERGER_2025.get(name, [])
    total_pop, total_area = 0, 0.0
    constituents = []
    for old in old_names:
        d = GSO_PROVINCE_DATA.get(old)
        if d:
            p, a = d["population"], d["area_km2"]
            total_pop += p
            total_area += a
            constituents.append({"name": old, "population": p,
                                 "area_km2": a,
                                 "density_per_km2": round(p / a, 1) if a else 0})
    return {
        "name": name, "population": total_pop,
        "area_km2": round(total_area, 2),
        "density_per_km2": round(total_pop / total_area, 1) if total_area else 0,
        "constituents": constituents, "is_merged": len(old_names) > 1,
    }


def _strip_holes(geom):
    """Remove interior holes/slivers from polygons for cleaner web rendering."""
    if geom is None or geom.is_empty:
        return geom
    if isinstance(geom, Polygon):
        return Polygon(geom.exterior)
    if isinstance(geom, MultiPolygon):
        polys = [Polygon(p.exterior) for p in geom.geoms if not p.is_empty]
        return MultiPolygon(polys) if polys else geom
    if isinstance(geom, GeometryCollection):
        polys = []
        for g in geom.geoms:
            if isinstance(g, Polygon):
                polys.append(Polygon(g.exterior))
            elif isinstance(g, MultiPolygon):
                polys.extend([Polygon(p.exterior) for p in g.geoms if not p.is_empty])
        return MultiPolygon(polys) if polys else geom
    return geom

# ── GADM loader (cached) ──────────────────────────────
_gadm_gdf = None
_boundaries_cache = None

def _load_gadm() -> gpd.GeoDataFrame:
    global _gadm_gdf
    if _gadm_gdf is not None:
        return _gadm_gdf
    GADM_CACHE.parent.mkdir(parents=True, exist_ok=True)
    if not GADM_CACHE.exists():
        for p in DATA_DIR.glob("*/raw/gadm41_VNM_1.json"):
            shutil.copy2(p, GADM_CACHE)
            break
        else:
            download_file(GADM_URL, GADM_CACHE, "GADM Vietnam")
    if not GADM_CACHE.exists():
        raise RuntimeError("Cannot load GADM boundary data")
    _gadm_gdf = gpd.read_file(GADM_CACHE)
    return _gadm_gdf

def _build_merged_boundaries():
    """Build 34-province merged GeoJSON (cached)."""
    global _boundaries_cache
    if _boundaries_cache is not None:
        return _boundaries_cache
    gdf = _load_gadm()
    features = []
    for new_name, old_names in sorted(PROVINCE_MERGER_2025.items()):
        parts = []
        for old in old_names:
            q = _normalize_vn(old)
            normed = gdf["NAME_1"].apply(_normalize_vn)
            m = gdf[normed == q]
            if not m.empty:
                parts.append(m.iloc[0].geometry)
        if not parts:
            continue
        geom = unary_union(parts) if len(parts) > 1 else parts[0]
        try:
            geom = geom.buffer(0)
        except Exception:
            pass
        geom = _strip_holes(geom)
        gs = gpd.GeoSeries([geom], crs=gdf.crs).to_crs("EPSG:4326")
        geojson_geom = json.loads(gs.to_json())["features"][0]["geometry"]
        gso = _gso(new_name)
        features.append({
            "type": "Feature",
            "geometry": geojson_geom,
            "properties": {
                "name": new_name,
                "population": gso["population"],
                "area_km2": gso["area_km2"],
                "density_per_km2": gso["density_per_km2"],
                "is_merged": gso["is_merged"],
                "processed": (_pdir(new_name) / "boundary.geojson").exists(),
            },
        })
    _boundaries_cache = {"type": "FeatureCollection", "features": features}
    return _boundaries_cache

# ── Auto-scale: percentile-based vmin/vmax ─────────────

def _get_layer_range(pdir: Path, layer: str) -> tuple:
    """Return (vmin, vmax) for a raster layer, using cached percentile stats."""
    safe_name = pdir.name
    key = (safe_name, layer)
    if key in _stats_cache:
        return _stats_cache[key]

    cfg = LAYER_CONFIG.get(layer)
    if cfg:
        fallback = (cfg["vmin"], cfg["vmax"])
    else:
        fallback = (0, 1)

    tif = pdir / f"{layer}.tif"
    if not tif.exists():
        tif = pdir / "native" / f"{layer}.tif"
    if not tif.exists():
        _stats_cache[key] = fallback
        return fallback

    try:
        with rasterio.open(tif) as src:
            data = src.read(1).astype(float)
            nd = src.nodata
        if nd is not None:
            data[data == nd] = np.nan
        valid = data[~np.isnan(data)]
        if len(valid) == 0:
            _stats_cache[key] = fallback
            return fallback
        vmin = float(np.percentile(valid, 2))
        vmax = float(np.percentile(valid, 98))
        if vmax - vmin < 1e-6:
            vmin, vmax = fallback
        _stats_cache[key] = (vmin, vmax)
        return (vmin, vmax)
    except Exception:
        _stats_cache[key] = fallback
        return fallback


# ── Tile renderer ──────────────────────────────────────

def _render_tile(data: np.ndarray, mask: np.ndarray, layer: str,
                 vmin: float = 0, vmax: float = 1) -> bytes:
    """Colorize a single-band tile array → RGBA PNG bytes."""
    h, w = data.shape

    if layer == "landcover":
        rgba = np.zeros((h, w, 4), dtype=np.uint8)
        for cls_id, (_, _, color) in LANDCOVER_CLASSES.items():
            r = int(color[1:3], 16)
            g = int(color[3:5], 16)
            b = int(color[5:7], 16)
            rgba[data == cls_id] = [r, g, b, 200]
        rgba[mask == 0, 3] = 0
    else:
        cfg = LAYER_CONFIG.get(layer, {"cmap": "viridis"})
        cmap = mpl_cm.get_cmap(cfg["cmap"])
        normed = np.clip((data.astype(float) - vmin) / max(vmax - vmin, 1e-6), 0, 1)
        rgba = (cmap(normed) * 255).astype(np.uint8)
        rgba[..., 3] = np.where(mask > 0, 200, 0)

    buf = io.BytesIO()
    Image.fromarray(rgba, "RGBA").save(buf, "PNG", optimize=True)
    return buf.getvalue()

# ═══════════════════════════════════════════════════════
#  API ROUTES
# ═══════════════════════════════════════════════════════

@app.get("/")
async def index():
    if FRONTEND_DIST_DIR.exists() and (FRONTEND_DIST_DIR / "index.html").exists():
        return FileResponse(FRONTEND_DIST_DIR / "index.html")
    return FileResponse(LEGACY_STATIC_DIR / "index.html")


@app.get("/api/provinces")
async def list_provinces():
    result = []
    for name in sorted(PROVINCE_MERGER_2025.keys()):
        info = _gso(name)
        info["processed"] = (_pdir(name) / "boundary.geojson").exists()
        result.append(info)
    return result


@app.get("/api/provinces/boundaries")
async def all_boundaries():
    return JSONResponse(_build_merged_boundaries())


@app.get("/api/provinces/{name}/boundary")
async def province_boundary(name: str):
    matched = _resolve(name)
    if not matched:
        raise HTTPException(404, f"Province '{name}' not found")
    pdir = _pdir(matched)
    out = {"boundary": None, "internal": None}
    bp = pdir / "boundary.geojson"
    if bp.exists():
        boundary_json = json.loads(bp.read_text(encoding="utf-8"))
        try:
            gdf_b = gpd.GeoDataFrame.from_features(boundary_json["features"], crs="EPSG:4326")
            gdf_b["geometry"] = gdf_b.geometry.apply(_strip_holes)
            out["boundary"] = json.loads(gdf_b.to_json())
        except Exception:
            out["boundary"] = boundary_json
    ibp = pdir / "internal_boundaries.geojson"
    if ibp.exists():
        out["internal"] = json.loads(ibp.read_text(encoding="utf-8"))
    if out["boundary"] is None:
        raise HTTPException(404, "Boundary not found – run pipeline first")
    return out


@app.get("/api/provinces/{name}/layers")
async def province_layers(name: str):
    matched = _resolve(name)
    if not matched:
        raise HTTPException(404)
    pdir = _pdir(matched)
    if not pdir.exists():
        return {"raster": [], "vector": []}

    rasters = []
    for lyr in ["hillshade", "dem", "slope", "aspect", "landcover"]:
        for sub in ["", "native"]:
            p = pdir / sub / f"{lyr}.tif" if sub else pdir / f"{lyr}.tif"
            if p.exists():
                rasters.append(lyr)
                break

    vectors = []
    for lyr, ext in [("infrastructure", ".gpkg"), ("contour", ".shp")]:
        if (pdir / f"{lyr}{ext}").exists():
            vectors.append(lyr)

    return {"raster": rasters, "vector": vectors}


@app.get("/api/provinces/{name}/stats")
async def province_stats(name: str):
    matched = _resolve(name)
    if not matched:
        raise HTTPException(404)
    pdir = _pdir(matched)

    result = _gso(matched)

    rp = pdir / "socioeconomic_report.json"
    if rp.exists():
        result["socioeconomic"] = json.loads(rp.read_text(encoding="utf-8"))

    gp = pdir / "gso_population.json"
    if gp.exists():
        result["gso_detail"] = json.loads(gp.read_text(encoding="utf-8"))

    return result


@app.get("/api/provinces/{name}/vector/{layer}")
async def province_vector(name: str, layer: str,
                          simplify: float = Query(0.0015),
                          max_features: int = Query(20000, ge=500, le=100000)):
    matched = _resolve(name)
    if not matched:
        raise HTTPException(404)
    pdir = _pdir(matched)

    ext_map = {"roads": ".gpkg", "rivers": ".gpkg",
               "infrastructure": ".gpkg", "contour": ".shp"}
    ext = ext_map.get(layer)
    if not ext:
        raise HTTPException(404, f"Unknown vector layer: {layer}")
    fp = pdir / f"{layer}{ext}"
    if not fp.exists():
        raise HTTPException(404, f"Layer '{layer}' not processed")

    gdf = gpd.read_file(fp)
    if gdf.crs and str(gdf.crs) != "EPSG:4326":
        gdf = gdf.to_crs("EPSG:4326")
    if simplify > 0:
        gdf["geometry"] = gdf.geometry.simplify(simplify)
    gdf = gdf[gdf.geometry.notnull()].copy()

    # Large province-wide OSM layers can freeze the browser if sent raw.
    if len(gdf) > max_features:
        stride = max(1, int(math.ceil(len(gdf) / max_features)))
        gdf = gdf.iloc[::stride].copy()

    return JSONResponse(json.loads(gdf.to_json()))


def _tile_bounds(z: int, x: int, y: int):
    """Convert ZXY slippy-map tile to Web Mercator (EPSG:3857) bounds."""
    n = 2.0 ** z
    def _lng(tx):
        return tx / n * 360.0 - 180.0
    def _lat(ty):
        lat_rad = math.atan(math.sinh(math.pi * (1 - 2 * ty / n)))
        return math.degrees(lat_rad)
    west, east = _lng(x), _lng(x + 1)
    north, south = _lat(y), _lat(y + 1)
    mx0, my0 = _TO_3857.transform(west, south)
    mx1, my1 = _TO_3857.transform(east, north)
    return mx0, my0, mx1, my1


@app.get("/api/provinces/{name}/tiles/{layer}/{z}/{x}/{y}.png")
async def tile(name: str, layer: str, z: int, x: int, y: int):
    matched = _resolve(name)
    if not matched:
        raise HTTPException(404)

    pdir = _pdir(matched)

    # Disk cache: serve pre-rendered tile if available
    cache_path = pdir / "tiles" / layer / str(z) / str(x) / f"{y}.png"
    if cache_path.exists():
        return FileResponse(cache_path, media_type="image/png",
                            headers={"Cache-Control": "public, max-age=86400"})

    tif = pdir / f"{layer}.tif"
    if not tif.exists():
        tif = pdir / "native" / f"{layer}.tif"
    if not tif.exists():
        return Response(content=_empty_tile(), media_type="image/png")

    try:
        tile_bounds = _tile_bounds(z, x, y)
        dst_transform = from_bounds(*tile_bounds, 256, 256)

        with rasterio.open(tif) as src:
            src_bounds_3857 = transform_bounds(src.crs, "EPSG:3857", *src.bounds)
            tb = tile_bounds
            if (tb[2] < src_bounds_3857[0] or tb[0] > src_bounds_3857[2] or
                    tb[3] < src_bounds_3857[1] or tb[1] > src_bounds_3857[3]):
                return Response(content=_empty_tile(), media_type="image/png")

            is_categorical = layer in ("landcover",)
            resamp = Resampling.nearest if is_categorical else Resampling.bilinear
            nodata = src.nodata
            dtype = src.dtypes[0]

            dst_data = np.zeros((256, 256), dtype=dtype)
            reproject(
                source=rasterio.band(src, 1),
                destination=dst_data,
                src_transform=src.transform,
                src_crs=src.crs,
                dst_transform=dst_transform,
                dst_crs="EPSG:3857",
                resampling=resamp,
                dst_nodata=nodata,
            )

        mask = np.ones((256, 256), dtype=np.uint8) * 255
        if nodata is not None:
            mask[dst_data == nodata] = 0
        mask[np.isnan(dst_data.astype(float))] = 0

        vmin, vmax = _get_layer_range(pdir, layer)
        content = _render_tile(dst_data.astype(float), mask, layer,
                               vmin=vmin, vmax=vmax)

        # Write to disk cache for future requests
        try:
            cache_path.parent.mkdir(parents=True, exist_ok=True)
            cache_path.write_bytes(content)
        except Exception:
            pass

        return Response(content=content, media_type="image/png",
                        headers={"Cache-Control": "public, max-age=86400"})
    except Exception:
        return Response(content=_empty_tile(), media_type="image/png")


@app.get("/api/landcover-classes")
async def landcover_classes():
    return {str(k): {"full": v[0], "short": v[1], "color": v[2]}
            for k, v in LANDCOVER_CLASSES.items()}


# ── Processing mode (disabled in web) ──────────────────

@app.post("/api/provinces/{name}/process")
async def start_processing(name: str):
    matched = _resolve(name)
    if not matched:
        raise HTTPException(404, f"Province '{name}' not found")
    p = _pdir(matched)
    cmd = f'python pipeline.py --province "{matched}"'
    if p.exists():
        cmd += " --resolution 5"
    return JSONResponse(
        status_code=405,
        content={
            "status": "disabled",
            "message": (
                "Pipeline execution from website is disabled. "
                "Run pipeline locally/offline, then refresh website."
            ),
            "command": cmd,
        },
    )


@app.get("/api/provinces/{name}/process/status")
async def processing_status(name: str):
    matched = _resolve(name)
    if not matched:
        raise HTTPException(404)
    return {
        "status": "disabled",
        "message": "Web processing disabled. This website reads local precomputed data only.",
    }
