#!/usr/bin/env python3
"""
Vietnam GIS Explorer – FastAPI Web Application.

Serves interactive maps and data generated by pipeline.py.

Usage:
    uvicorn app:app --reload --host 0.0.0.0 --port 8000
"""

import io
import json
import logging
import shutil
import threading
from functools import lru_cache
from pathlib import Path
from typing import Optional, Dict, Tuple

import math

import numpy as np
import rasterio
from rasterio.warp import reproject, Resampling, transform_bounds
from rasterio.transform import from_bounds
from rasterio.windows import Window, from_bounds as window_from_bounds
from rasterio.features import rasterize
import geopandas as gpd
from shapely.geometry import Polygon, MultiPolygon, GeometryCollection, shape
from shapely.ops import unary_union, transform as shapely_transform
from PIL import Image
from fastapi import FastAPI, HTTPException, Query
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse, Response, JSONResponse

from pipeline import (
    PROVINCE_MERGER_2025, GSO_PROVINCE_DATA, GADM_URL,
    LANDCOVER_CLASSES, _normalize_vn, download_file,
)

from pyproj import Transformer

import matplotlib
matplotlib.use("Agg")
import matplotlib.cm as mpl_cm

_TO_3857 = Transformer.from_crs("EPSG:4326", "EPSG:3857", always_xy=True)

log = logging.getLogger(__name__)

# Limit concurrent GDAL warp ops (each can allocate tens of MB; parallel tile
# bursts at high zoom otherwise exhaust RAM and crash the process).
_GDAL_WARP_SEMAPHORE = threading.BoundedSemaphore(4)
# Window reads larger than this fall back to band-based warp (low zoom / overview path).
_MAX_WINDOW_PIXELS = 12_000_000
# Slippy-map zoom above which we still serve tiles; extreme z values are wasteful.
_MAX_TILE_ZOOM = 18

# ── Paths ──────────────────────────────────────────────
BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data" / "province"
COLLECTED_DIR = BASE_DIR / "data" / "collected"
GADM_CACHE = BASE_DIR / "data" / "gadm41_VNM_1.json"
LEGACY_STATIC_DIR = BASE_DIR / "static"
FRONTEND_DIST_DIR = BASE_DIR / "frontend" / "dist"
FRONTEND_ASSETS_DIR = FRONTEND_DIST_DIR / "assets"

# Some provinces are merged in 2025; collected datasets may still be stored
# under their historical province folder.
COLLECTED_PROVINCE_MAP: Dict[str, str] = {
    # Quảng Nam is currently merged into Đà Nẵng in this project.
    "Đà Nẵng": "Quảng_Nam",
}

# ── Layer rendering config ─────────────────────────────
LAYER_CONFIG: Dict[str, dict] = {
    "hillshade":  {"cmap": "gray",        "vmin": 0,    "vmax": 255},
    "dem":        {"cmap": "gist_earth",   "vmin": 0,    "vmax": 2500},
    "slope":      {"cmap": "YlOrRd",       "vmin": 0,    "vmax": 45},
    "aspect":     {"cmap": "twilight",     "vmin": 0,    "vmax": 360},
    # Landslide susceptibility (Quảng Nam mountain districts)
    "p_lsi":      {"cmap": "YlOrRd",       "vmin": 0,    "vmax": 1},
}

_NEAREST_LAYERS = {"landcover", "aspect", "c_lsi"}

# Per-province auto-scale cache: {(province_safe, layer): (vmin, vmax)}
_stats_cache: Dict[tuple, tuple] = {}

# ── Transparent 256x256 tile (lazy) ────────────────────
_EMPTY_PNG: Optional[bytes] = None

def _empty_tile() -> bytes:
    global _EMPTY_PNG
    if _EMPTY_PNG is None:
        buf = io.BytesIO()
        Image.new("RGBA", (256, 256), (0, 0, 0, 0)).save(buf, "PNG")
        _EMPTY_PNG = buf.getvalue()
    return _EMPTY_PNG


def _png_tile_cache_valid(cache_path: Path, tif_path: Path) -> bool:
    """Use on-disk tile only if it is newer than the GeoTIFF and stats sidecar."""
    if not cache_path.exists():
        return False
    try:
        png_m = cache_path.stat().st_mtime
        if png_m < tif_path.stat().st_mtime:
            return False
        stats = tif_path.with_suffix(".stats.json")
        if stats.exists() and png_m < stats.stat().st_mtime:
            return False
        return True
    except OSError:
        return False


def _tile_bounds(z: int, x: int, y: int):
    """Convert ZXY slippy-map tile to Web Mercator (EPSG:3857) bounds."""
    n = 2.0 ** z

    def _lng(tx):
        return tx / n * 360.0 - 180.0

    def _lat(ty):
        lat_rad = math.atan(math.sinh(math.pi * (1 - 2 * ty / n)))
        return math.degrees(lat_rad)

    west, east = _lng(x), _lng(x + 1)
    north, south = _lat(y), _lat(y + 1)
    mx0, my0 = _TO_3857.transform(west, south)
    mx1, my1 = _TO_3857.transform(east, north)
    return mx0, my0, mx1, my1


@lru_cache(maxsize=128)
def _province_geom_3857(province_name: str):
    """Province boundary geometry in EPSG:3857 for masking tiles."""
    pdir = _pdir(province_name)
    bp = pdir / "boundary.geojson"
    geom_4326 = None
    if bp.exists():
        try:
            boundary_json = json.loads(bp.read_text(encoding="utf-8"))
            gdf_b = gpd.GeoDataFrame.from_features(boundary_json["features"], crs="EPSG:4326")
            geom_4326 = unary_union(gdf_b.geometry)
        except Exception:
            geom_4326 = None
    if geom_4326 is None:
        try:
            fc = _build_merged_boundaries()
            for f in fc.get("features", []):
                if f.get("properties", {}).get("name") == province_name:
                    geom_4326 = shape(f.get("geometry"))
                    break
        except Exception:
            geom_4326 = None
    if geom_4326 is None:
        return None
    try:
        return shapely_transform(lambda x, y: _TO_3857.transform(x, y), geom_4326)
    except Exception:
        return None


# ── In-memory rendered tile LRU cache ─────────────────
# One open dataset per render; never share handles across threads. Cap concurrent
# GDAL warps and warp RAM so parallel z14+ tile storms do not OOM the process.
@lru_cache(maxsize=4096)
def _cached_tile_render(tif_path: str, layer: str, z: int, x: int, y: int,
                        vmin: float, vmax: float, province_name: str) -> bytes:
    """Reproject + colorize a tile, cached by coordinates."""
    tile_bounds = _tile_bounds(z, x, y)
    dst_transform = from_bounds(*tile_bounds, 256, 256)

    prov_geom = _province_geom_3857(province_name)

    with _GDAL_WARP_SEMAPHORE:
        with rasterio.Env(
            GDAL_WARP_MEMORY_LIMIT=128,
            GDAL_NUM_THREADS=1,
        ):
            try:
                with rasterio.open(tif_path) as src:
                    src_bounds_3857 = transform_bounds(
                        src.crs, "EPSG:3857", *src.bounds
                    )
                    tb = tile_bounds
                    if (tb[2] < src_bounds_3857[0] or tb[0] > src_bounds_3857[2]
                            or tb[3] < src_bounds_3857[1]
                            or tb[1] > src_bounds_3857[3]):
                        return _empty_tile()

                    west, south, east, north = tb[0], tb[1], tb[2], tb[3]
                    left, bottom, right, top = transform_bounds(
                        "EPSG:3857", src.crs,
                        west, south, east, north,
                        densify_pts=21,
                    )

                    nodata = src.nodata
                    dtype = src.dtypes[0]
                    fill_val = nodata if nodata is not None else -9999.0
                    dst_data = np.full((256, 256), fill_val, dtype=dtype)
                    resamp = (
                        Resampling.nearest if layer in _NEAREST_LAYERS
                        else Resampling.bilinear
                    )

                    window = window_from_bounds(
                        left, bottom, right, top, src.transform
                    ).intersection(Window(0, 0, src.width, src.height))

                    if window.width < 1 or window.height < 1:
                        return _empty_tile()

                    win_pixels = int(window.width) * int(window.height)
                    if win_pixels <= _MAX_WINDOW_PIXELS:
                        src_arr = src.read(1, window=window)
                        src_tf = src.window_transform(window)
                        reproject(
                            source=src_arr,
                            destination=dst_data,
                            src_transform=src_tf,
                            src_crs=src.crs,
                            dst_transform=dst_transform,
                            dst_crs="EPSG:3857",
                            resampling=resamp,
                            dst_nodata=fill_val,
                        )
                    else:
                        reproject(
                            source=rasterio.band(src, 1),
                            destination=dst_data,
                            src_transform=src.transform,
                            src_crs=src.crs,
                            dst_transform=dst_transform,
                            dst_crs="EPSG:3857",
                            resampling=resamp,
                            dst_nodata=fill_val,
                        )

                mask = np.ones((256, 256), dtype=np.uint8) * 255
                float_data = dst_data.astype(float)
                # Float nodata must not use == (warp leaves values near -9999); unmasked
                # nodata maps to black in grayscale — looks like random dark rectangles.
                if np.issubdtype(dtype, np.floating):
                    invalid = np.isnan(float_data) | np.isclose(
                        float_data, float(fill_val), rtol=0, atol=1e-2
                    )
                else:
                    invalid = float_data == fill_val
                mask[invalid] = 0

                # Province crop/mask: clip the rendered tile to the province boundary.
                if prov_geom is not None:
                    try:
                        bmask = rasterize(
                            [(prov_geom, 1)],
                            out_shape=(256, 256),
                            transform=dst_transform,
                            fill=0,
                            dtype="uint8",
                            all_touched=False,
                        )
                        mask[bmask == 0] = 0
                    except Exception:
                        pass

                return _render_tile(float_data, mask, layer, vmin=vmin, vmax=vmax)
            except Exception as e:
                log.warning("Tile render failed for %s z=%s: %s", tif_path, z, e)
                return _empty_tile()

# ── FastAPI app ────────────────────────────────────────
app = FastAPI(title="Vietnam GIS Explorer", version="1.0")
if LEGACY_STATIC_DIR.exists():
    app.mount("/static", StaticFiles(directory=str(LEGACY_STATIC_DIR)), name="static")
if FRONTEND_ASSETS_DIR.exists():
    app.mount("/assets", StaticFiles(directory=str(FRONTEND_ASSETS_DIR)), name="assets")

# ── Helpers ────────────────────────────────────────────

def _safe(name: str) -> str:
    return name.replace(" ", "_").replace(".", "")

def _pdir(name: str) -> Path:
    return DATA_DIR / _safe(name)

def _collected_dir_for_province(name: str) -> Optional[Path]:
    mapped = COLLECTED_PROVINCE_MAP.get(name)
    if not mapped:
        return None
    p = COLLECTED_DIR / mapped
    return p if p.exists() else None

def _resolve_raster_path(pdir: Path, province_name: str, layer: str) -> Optional[Path]:
    tif = pdir / f"{layer}.tif"
    if not tif.exists():
        tif = pdir / "native" / f"{layer}.tif"
    if tif.exists():
        return tif
    cdir = _collected_dir_for_province(province_name)
    if cdir:
        tif2 = cdir / f"{layer}.tif"
        if tif2.exists():
            return tif2
    return None

def _resolve_vector_path(pdir: Path, province_name: str, layer: str) -> Optional[Path]:
    ext_map = {"roads": ".gpkg", "rivers": ".gpkg",
               "infrastructure": ".gpkg", "contour": ".shp",
               "real_ls_point": ".shp"}
    ext = ext_map.get(layer)
    if not ext:
        return None
    fp = pdir / f"{layer}{ext}"
    if fp.exists():
        return fp
    cdir = _collected_dir_for_province(province_name)
    if cdir:
        fp2 = cdir / f"{layer}{ext}"
        if fp2.exists():
            return fp2
    return None

def _resolve(query: str) -> Optional[str]:
    """Match a query string to a canonical 2025 province name."""
    q = _normalize_vn(query)
    for new_name in PROVINCE_MERGER_2025:
        if _normalize_vn(new_name) == q or q in _normalize_vn(new_name):
            return new_name
    for new_name, old_names in PROVINCE_MERGER_2025.items():
        for old in old_names:
            if _normalize_vn(old) == q or q in _normalize_vn(old):
                return new_name
    return None

def _gso(name: str) -> dict:
    old_names = PROVINCE_MERGER_2025.get(name, [])
    total_pop, total_area = 0, 0.0
    constituents = []
    for old in old_names:
        d = GSO_PROVINCE_DATA.get(old)
        if d:
            p, a = d["population"], d["area_km2"]
            total_pop += p
            total_area += a
            constituents.append({"name": old, "population": p,
                                 "area_km2": a,
                                 "density_per_km2": round(p / a, 1) if a else 0})
    return {
        "name": name, "population": total_pop,
        "area_km2": round(total_area, 2),
        "density_per_km2": round(total_pop / total_area, 1) if total_area else 0,
        "constituents": constituents, "is_merged": len(old_names) > 1,
    }


def _strip_holes(geom):
    """Remove interior holes/slivers from polygons for cleaner web rendering."""
    if geom is None or geom.is_empty:
        return geom
    if isinstance(geom, Polygon):
        return Polygon(geom.exterior)
    if isinstance(geom, MultiPolygon):
        polys = [Polygon(p.exterior) for p in geom.geoms if not p.is_empty]
        return MultiPolygon(polys) if polys else geom
    if isinstance(geom, GeometryCollection):
        polys = []
        for g in geom.geoms:
            if isinstance(g, Polygon):
                polys.append(Polygon(g.exterior))
            elif isinstance(g, MultiPolygon):
                polys.extend([Polygon(p.exterior) for p in g.geoms if not p.is_empty])
        return MultiPolygon(polys) if polys else geom
    return geom

# ── GADM loader (cached) ──────────────────────────────
_gadm_gdf = None
_boundaries_cache = None

def _load_gadm() -> gpd.GeoDataFrame:
    global _gadm_gdf
    if _gadm_gdf is not None:
        return _gadm_gdf
    GADM_CACHE.parent.mkdir(parents=True, exist_ok=True)
    if not GADM_CACHE.exists():
        for p in DATA_DIR.glob("*/raw/gadm41_VNM_1.json"):
            shutil.copy2(p, GADM_CACHE)
            break
        else:
            download_file(GADM_URL, GADM_CACHE, "GADM Vietnam")
    if not GADM_CACHE.exists():
        raise RuntimeError("Cannot load GADM boundary data")
    _gadm_gdf = gpd.read_file(GADM_CACHE)
    return _gadm_gdf

def _build_merged_boundaries():
    """Build 34-province merged GeoJSON (cached)."""
    global _boundaries_cache
    if _boundaries_cache is not None:
        return _boundaries_cache
    gdf = _load_gadm()
    features = []
    for new_name, old_names in sorted(PROVINCE_MERGER_2025.items()):
        parts = []
        for old in old_names:
            q = _normalize_vn(old)
            normed = gdf["NAME_1"].apply(_normalize_vn)
            m = gdf[normed == q]
            if not m.empty:
                parts.append(m.iloc[0].geometry)
        if not parts:
            continue
        geom = unary_union(parts) if len(parts) > 1 else parts[0]
        try:
            geom = geom.buffer(0)
        except Exception:
            pass
        geom = _strip_holes(geom)
        gs = gpd.GeoSeries([geom], crs=gdf.crs).to_crs("EPSG:4326")
        geojson_geom = json.loads(gs.to_json())["features"][0]["geometry"]
        gso = _gso(new_name)
        features.append({
            "type": "Feature",
            "geometry": geojson_geom,
            "properties": {
                "name": new_name,
                "population": gso["population"],
                "area_km2": gso["area_km2"],
                "density_per_km2": gso["density_per_km2"],
                "is_merged": gso["is_merged"],
                "processed": (_pdir(new_name) / "boundary.geojson").exists(),
            },
        })
    _boundaries_cache = {"type": "FeatureCollection", "features": features}
    return _boundaries_cache

# ── Auto-scale: percentile-based vmin/vmax ─────────────

def _get_layer_range_for_tif(pdir: Path, layer: str, tif: Path) -> Tuple[float, float]:
    """Return (vmin, vmax) for a raster layer, preferring sidecar stats JSON."""
    safe_name = pdir.name
    key = (safe_name, layer)
    if key in _stats_cache:
        return _stats_cache[key]

    cfg = LAYER_CONFIG.get(layer)
    fallback = (cfg["vmin"], cfg["vmax"]) if cfg else (0, 1)

    stats_file = tif.with_suffix(".stats.json")
    if stats_file.exists():
        try:
            s = json.loads(stats_file.read_text())
            # Stable rounding keeps LRU tile cache keys consistent across requests.
            result = (round(float(s["vmin"]), 4), round(float(s["vmax"]), 4))
            _stats_cache[key] = result
            return result
        except Exception:
            pass

    try:
        with rasterio.open(tif) as src:
            data = src.read(1).astype(float)
            nd = src.nodata
        if nd is not None:
            data[data == nd] = np.nan
        valid = data[~np.isnan(data)]
        if len(valid) == 0:
            _stats_cache[key] = fallback
            return fallback
        vmin = round(float(np.percentile(valid, 2)), 4)
        vmax = round(float(np.percentile(valid, 98)), 4)
        if vmax - vmin < 1e-6:
            vmin, vmax = fallback
        _stats_cache[key] = (vmin, vmax)
        return (vmin, vmax)
    except Exception:
        _stats_cache[key] = fallback
        return fallback


def _get_layer_range(pdir: Path, layer: str) -> Tuple[float, float]:
    """Backwards-compatible wrapper for province rasters."""
    tif = pdir / f"{layer}.tif"
    if not tif.exists():
        tif = pdir / "native" / f"{layer}.tif"
    if not tif.exists():
        cfg = LAYER_CONFIG.get(layer)
        return (cfg["vmin"], cfg["vmax"]) if cfg else (0, 1)
    return _get_layer_range_for_tif(pdir, layer, tif)


# ── Tile renderer ──────────────────────────────────────

_LC_LUT = np.zeros((256, 4), dtype=np.uint8)
for _cls_id, (_, _, _hex) in LANDCOVER_CLASSES.items():
    if _cls_id < 256:
        _LC_LUT[_cls_id] = [int(_hex[1:3], 16), int(_hex[3:5], 16),
                            int(_hex[5:7], 16), 220]

_CLSI_LUT = np.zeros((256, 4), dtype=np.uint8)
# 1-5: rất thấp, thấp, trung bình, cao, rất cao
_CLSI_COLORS = {
    1: "#2c7bb6",  # very low (blue)
    2: "#abd9e9",  # low (light blue)
    3: "#ffffbf",  # medium (yellow)
    4: "#fdae61",  # high (orange)
    5: "#d7191c",  # very high (red)
}
for _k, _hex in _CLSI_COLORS.items():
    _CLSI_LUT[_k] = [int(_hex[1:3], 16), int(_hex[3:5], 16),
                     int(_hex[5:7], 16), 230]

def _render_tile(data: np.ndarray, mask: np.ndarray, layer: str,
                 vmin: float = 0, vmax: float = 1) -> bytes:
    """Colorize a single-band tile array to RGBA PNG bytes."""
    h, w = data.shape

    if layer == "landcover":
        idx = np.clip(data.astype(int), 0, 255)
        rgba = _LC_LUT[idx].copy()
        rgba[mask == 0, 3] = 0
    elif layer == "c_lsi":
        idx = np.clip(data.astype(int), 0, 255)
        rgba = _CLSI_LUT[idx].copy()
        rgba[mask == 0, 3] = 0
    else:
        cfg = LAYER_CONFIG.get(layer, {"cmap": "viridis"})
        cmap = mpl_cm.get_cmap(cfg["cmap"])
        normed = np.clip((data - vmin) / max(vmax - vmin, 1e-6), 0, 1)
        rgba = (cmap(normed) * 255).astype(np.uint8)
        rgba[..., 3] = np.where(mask > 0, 220, 0)

    buf = io.BytesIO()
    Image.fromarray(rgba, "RGBA").save(buf, "PNG")
    return buf.getvalue()

# ═══════════════════════════════════════════════════════
#  API ROUTES
# ═══════════════════════════════════════════════════════

@app.get("/")
async def index():
    if FRONTEND_DIST_DIR.exists() and (FRONTEND_DIST_DIR / "index.html").exists():
        return FileResponse(FRONTEND_DIST_DIR / "index.html")
    return FileResponse(LEGACY_STATIC_DIR / "index.html")


@app.get("/api/provinces")
async def list_provinces():
    result = []
    for name in sorted(PROVINCE_MERGER_2025.keys()):
        info = _gso(name)
        info["processed"] = (_pdir(name) / "boundary.geojson").exists()
        result.append(info)
    return result


@app.get("/api/provinces/boundaries")
async def all_boundaries():
    return JSONResponse(_build_merged_boundaries())


@app.get("/api/provinces/{name}/boundary")
async def province_boundary(name: str):
    matched = _resolve(name)
    if not matched:
        raise HTTPException(404, f"Province '{name}' not found")
    pdir = _pdir(matched)
    out = {"boundary": None, "internal": None}
    bp = pdir / "boundary.geojson"
    if bp.exists():
        boundary_json = json.loads(bp.read_text(encoding="utf-8"))
        try:
            gdf_b = gpd.GeoDataFrame.from_features(boundary_json["features"], crs="EPSG:4326")
            gdf_b["geometry"] = gdf_b.geometry.apply(_strip_holes)
            out["boundary"] = json.loads(gdf_b.to_json())
        except Exception:
            out["boundary"] = boundary_json
    ibp = pdir / "internal_boundaries.geojson"
    if ibp.exists():
        out["internal"] = json.loads(ibp.read_text(encoding="utf-8"))
    if out["boundary"] is None:
        raise HTTPException(404, "Boundary not found – run pipeline first")
    return out


@app.get("/api/provinces/{name}/layers")
async def province_layers(name: str):
    matched = _resolve(name)
    if not matched:
        raise HTTPException(404)
    pdir = _pdir(matched)
    if not pdir.exists():
        return {"raster": [], "vector": []}

    rasters = []
    for lyr in ["hillshade", "dem", "slope", "aspect", "landcover", "p_lsi", "c_lsi"]:
        if _resolve_raster_path(pdir, matched, lyr):
            rasters.append(lyr)

    vectors = []
    for lyr in ["infrastructure", "contour", "real_ls_point"]:
        if _resolve_vector_path(pdir, matched, lyr):
            vectors.append(lyr)

    return {"raster": rasters, "vector": vectors}


@app.get("/api/provinces/{name}/stats")
async def province_stats(name: str):
    matched = _resolve(name)
    if not matched:
        raise HTTPException(404)
    pdir = _pdir(matched)

    result = _gso(matched)

    rp = pdir / "socioeconomic_report.json"
    if rp.exists():
        result["socioeconomic"] = json.loads(rp.read_text(encoding="utf-8"))

    gp = pdir / "gso_population.json"
    if gp.exists():
        result["gso_detail"] = json.loads(gp.read_text(encoding="utf-8"))

    return result


@app.get("/api/provinces/{name}/vector/{layer}")
async def province_vector(name: str, layer: str,
                          simplify: float = Query(0.0015),
                          max_features: int = Query(20000, ge=500, le=100000)):
    matched = _resolve(name)
    if not matched:
        raise HTTPException(404)
    pdir = _pdir(matched)

    fp = _resolve_vector_path(pdir, matched, layer)
    if not fp:
        raise HTTPException(404, f"Unknown or missing vector layer: {layer}")

    gdf = gpd.read_file(fp)
    if gdf.crs and str(gdf.crs) != "EPSG:4326":
        gdf = gdf.to_crs("EPSG:4326")
    if simplify > 0:
        gdf["geometry"] = gdf.geometry.simplify(simplify)
    gdf = gdf[gdf.geometry.notnull()].copy()

    # Do not expose precise landslide coordinates. Reduce precision of geometries
    # before serializing (approx ~110m at 0.001 degrees).
    if layer == "real_ls_point":
        def _round_point_geom(geom):
            try:
                if geom is None or geom.is_empty:
                    return geom
                # Shapely Point
                x, y = geom.x, geom.y
                return type(geom)(round(float(x), 3), round(float(y), 3))
            except Exception:
                return geom
        gdf["geometry"] = gdf.geometry.apply(_round_point_geom)

    # Large province-wide OSM layers can freeze the browser if sent raw.
    if len(gdf) > max_features:
        stride = max(1, int(math.ceil(len(gdf) / max_features)))
        gdf = gdf.iloc[::stride].copy()

    return JSONResponse(json.loads(gdf.to_json()))


@app.get("/api/provinces/{name}/tiles/{layer}/{z}/{x}/{y}.png")
def tile(name: str, layer: str, z: int, x: int, y: int):
    matched = _resolve(name)
    if not matched:
        raise HTTPException(404)

    pdir = _pdir(matched)
    headers = {"Cache-Control": "public, max-age=86400"}

    cache_path = pdir / "tiles" / layer / str(z) / str(x) / f"{y}.png"
    tif = _resolve_raster_path(pdir, matched, layer)
    if not tif:
        return Response(content=_empty_tile(), media_type="image/png")

    if z < 0 or z > _MAX_TILE_ZOOM:
        return Response(content=_empty_tile(), media_type="image/png")

    if _png_tile_cache_valid(cache_path, tif):
        return FileResponse(cache_path, media_type="image/png", headers=headers)

    try:
        vmin, vmax = _get_layer_range_for_tif(pdir, layer, tif)
        content = _cached_tile_render(str(tif), layer, z, x, y, vmin, vmax, matched)

        try:
            cache_path.parent.mkdir(parents=True, exist_ok=True)
            cache_path.write_bytes(content)
        except Exception:
            pass

        return Response(content=content, media_type="image/png", headers=headers)
    except Exception:
        return Response(content=_empty_tile(), media_type="image/png")


@app.get("/api/landcover-classes")
async def landcover_classes():
    return {str(k): {"full": v[0], "short": v[1], "color": v[2]}
            for k, v in LANDCOVER_CLASSES.items()}


# ── Processing mode (disabled in web) ──────────────────

@app.post("/api/provinces/{name}/process")
async def start_processing(name: str):
    matched = _resolve(name)
    if not matched:
        raise HTTPException(404, f"Province '{name}' not found")
    p = _pdir(matched)
    cmd = f'python pipeline.py --province "{matched}"'
    if p.exists():
        cmd += " --resolution 5"
    return JSONResponse(
        status_code=405,
        content={
            "status": "disabled",
            "message": (
                "Pipeline execution from website is disabled. "
                "Run pipeline locally/offline, then refresh website."
            ),
            "command": cmd,
        },
    )


@app.get("/api/provinces/{name}/process/status")
async def processing_status(name: str):
    matched = _resolve(name)
    if not matched:
        raise HTTPException(404)
    return {
        "status": "disabled",
        "message": "Web processing disabled. This website reads local precomputed data only.",
    }
